### ISSUE TITLE
`(*tlsForwarder.)Forward` causes nil pointer dereference

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-telemetry#59]
### Problem Statement

When running KGO with telemetry enabled, the operator gets in `CrashLoopBackOff` status for a `nil pointer dereference` error.
I Installed KGO through the README guide in a Kind cluster.

Stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15d909e]

goroutine 308 [running]:
github.com/kong/kubernetes-telemetry/pkg/forwarders.(*tlsForwarder).Forward(0x0, {0x1c71e70?, 0xc0004fe140?}, {0xc000164240, 0x104, 0x120})
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/forwarders/tlsforwarder.go:66 +0x5e
github.com/kong/kubernetes-telemetry/pkg/telemetry.NewConsumer.func1()
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/telemetry/consumer.go:49 +0x1c3
created by github.com/kong/kubernetes-telemetry/pkg/telemetry.NewConsumer
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/telemetry/consumer.go:35 +0x171
```

**Comment by pmalek** [comment]
There's an issue for this already in here: https://github.com/Kong/gateway-operator/issues/200 but actually let's keep this one as well so that we can trick it in this repo.
